  name: Build
  on: [push, pull_request]
  jobs:
    build:
      name: Build project
      runs-on: ubuntu-latest

      steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Install dependencies
          run: npm install

        - name: Run build
          run: npm run build
